default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: TooYouApp_development

test:
  <<: *default
  database: TooYouApp_test

production:
  <<: *default
  database: TooYouApp_production
  username: TooYouApp
  password: <%= ENV['TOOYOUAPP_DATABASE_PASSWORD'] %>
