# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3791f3aeba7af07f152981abb1de9d224acbeb3a479388b07bfa2df291fe5a9e9c4be7dff649cba90a04c2cbf576ff49a86b880e0078ebb4520fb944f5bbb22d

test:
  secret_key_base: 6ee12fa294791f7304bb3ba21300777a729769c40a96b07d991898db783a8e7dbd5425d8be427a3cd0de152c8721b9480766f8319e869385b8b51a2ff640c56f

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
